CREATE DATABASE IF NOT EXISTS AMART ;

USE AMART ;




CREATE TABLE ADMIN (

    AD_ID VARCHAR(50) PRIMARY KEY ,
    AD_EMAIL_ID VARCHAR(100) UNIQUE ,
    AD_PASSWORD VARCHAR(100) ,
    AD_FIRSTNAME CHAR(100) ,
    AD_LASTNAME CHAR(100) ,
    AD_PHNO bigint(20)

);

CREATE TABLE LOGIN (

    LOGIN_ID VARCHAR(50) PRIMARY KEY ,
    EMAIL_ID VARCHAR(100) UNIQUE ,
    USER_PASSWORD VARCHAR(255) ,
    USER_FNAME VARCHAR(100) ,
    USER_PHNO bigint(20)

);

CREATE TABLE ADDRESS (

    ADD_ID INT PRIMARY KEY AUTO_INCREMENT ,
    ADD_LOGIN_ID VARCHAR(50) ,
    ADDRESS VARCHAR(255) ,
    PINCODE INT,

    FOREIGN KEY (ADD_LOGIN_ID) REFERENCES LOGIN (LOGIN_ID)

);

CREATE TABLE COOKIE (

    CK_ID bigint(11) PRIMARY KEY AUTO_INCREMENT ,
    CK_LOGIN_ID VARCHAR(50) ,
    CK_VALUE VARCHAR(300) ,

    FOREIGN KEY (CK_LOGIN_ID) REFERENCES LOGIN (LOGIN_ID)

);

CREATE TABLE CATEGORY (

    CAT_ID INT PRIMARY KEY AUTO_INCREMENT,
    CAT_NAME CHAR(20)

);



CREATE TABLE PRODUCT (

    PRD_CAT_ID INT ,
    PRD_ID VARCHAR(50) PRIMARY KEY ,
    PRD_NAME VARCHAR(100) ,
    PRD_DETAILS VARCHAR(255) ,
    PRD_PRICE FLOAT ,

    FOREIGN KEY (PRD_CAT_ID) REFERENCES CATEGORY (CAT_ID) 

);

CREATE TABLE PRD_IMAGE (

    IMG_PRD_ID VARCHAR(50),
    IMG_PATH VARCHAR(255),
    
    FOREIGN KEY (IMG_PRD_ID) REFERENCES PRODUCT (PRD_ID) 
);

CREATE TABLE CART (

    CRT_LOGIN_ID VARCHAR(50) ,
    CRT_PRD_ID VARCHAR(50) ,
    CRT_QUANTITY INT ,

    FOREIGN KEY (CRT_LOGIN_ID) REFERENCES LOGIN (LOGIN_ID) ,
    FOREIGN KEY (CRT_PRD_ID) REFERENCES PRODUCT (PRD_ID)

);

CREATE TABLE ORDERS (

    ORD_ID INT PRIMARY KEY AUTO_INCREMENT ,
    ORD_LOGIN_ID VARCHAR(50) ,
    ORD_PRD_ID VARCHAR(50),
    ORD_QUANTITY INT,

    FOREIGN KEY (ORD_LOGIN_ID) REFERENCES LOGIN (LOGIN_ID),
    FOREIGN KEY (ORD_PRD_ID) REFERENCES PRODUCT (PRD_ID)

);

CREATE TABLE TOTAL_AMT (

    AMT_ID INT PRIMARY KEY AUTO_INCREMENT,
    TA_ORDER_ID INT,
    TOTAL_AMT FLOAT,

    FOREIGN KEY (TA_ORDER_ID) REFERENCES ORDERS (ORD_ID)

);


INSERT INTO `category` (`CAT_ID`, `CAT_NAME`) VALUES ('2001', 'Electronics'), ('2002', 'Furniture'), ('2003', 'Kitchen'), ('2004', 'Bathroom')